# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-11 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20200711_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_added',
        ),
    ]
