# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-11 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entry_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='biaoti',
        ),
    ]
