# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-11 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20200711_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='biaoti',
            new_name='topic',
        ),
    ]
