# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-11 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20200711_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '45613456456'},
        ),
    ]
